basePath: /api
definitions:
  api.UserDetailsResponse:
    properties:
      favouriteNumber:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  description: Your API Description
  termsOfService: http://your-terms-of-service-url.com
  title: Your API Title
  version: "1.0"
paths:
  /test/super:
    get:
      consumes:
      - application/json
      description: get details of a user by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserDetailsResponse'
      security:
      - basicAuth: []
      summary: Get user details
      tags:
      - users
securityDefinitions:
  basicAuth:
    type: basic
swagger: "2.0"
