basePath: /api
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
      responseCode:
        type: integer
    type: object
  api.UserDetailsResponse:
    properties:
      favouriteNumber:
        type: integer
      username:
        type: string
    type: object
  api.UserDto:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
  handlers.CreateUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Your API Description
  termsOfService: http://your-terms-of-service-url.com
  title: Your API Title
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get details of a user by username
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserDetailsResponse'
      security:
      - basicAuth: []
      summary: Get user details
      tags:
      - users
    post:
      consumes:
      - application/json
      description: This API endpoint creates a new user with the provided username
        and password.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            $ref: '#/definitions/api.UserDto'
        "400":
          description: Invalid request format or parameters
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create a new user
      tags:
      - users
securityDefinitions:
  basicAuth:
    type: basic
swagger: "2.0"
